In [53]:
print('Hello World!')

import time

time.sleep(3)

def say_hello(recipient):
    return 'Hello {}'.format(recipient)
say_hello('Charles')


print('i' +' '+ 'love'+' ' + 'coding')
first_name="Charles"
last_name="Owuala"
full_name=first_name + " " + last_name
print(full_name)

first_name="charles"
print('my name is {}'.format(first_name))
print("Hello {}, you are {} today".format(first_name,27))


first_name="Charles"
print(f"hello {first_name}")

word="Charles"
print(word[5])

word="challengers"
print(word[0:9])

first_name="constance"
print(first_name.title())

first_name="constance"
print(first_name.upper())

first_name="CONSTANCE"
print(first_name.lower())

word="Wecome to Ghana, Clarke!"
print(word.replace('!', '.'))


sentence= "Welcome to the Data Science Extenship"
print(sentence.find('ship'))

x=10
y=4
if x>y:
    print("True")

x=10
z=42
if x>z:
    print("True")
else:
    print("False")

x=40
y=40
if x>y:
    print("True")
elif x==y:
    print("equal")
else:
    print("False")

Names = ["charles", "mike", "daniel", "sam"]
print(Names[2])


list = ["cat", "lion", "crocodile", ["goat", "pig", "fowl"], 70 ]
print(list[3])
list=list[3]
print(list[0])

student=["geoffery", 30, "Maria", "ope"]
print(student[1])
student[1]=34
print(student)

price=[23.5,41,11,4,7734,236]
price.sort()
print(price)

list=[23.5,41,"ade",11,4,"segun",7734,236]
print(type(list))

group=[23.5,41,11,4,7734,236]
group.append("one million")
print(group)


group=[23.5,41,11,4,7734,236]
group.extend(["one million", "gore-fest"])
print(group)

group=[23.5,41,11,4,7734,236]
print(group.index(41))

group=[23.5,41,11,4,7734,236]
print(" {} is the highest value in the group".format(max(group)))

group=[23.5,41,11,4,7734,236]
print(" {} is the lowest value in the group".format(min(group)))

group=[23.5,41,11,4,7734,236]
print(len(group))


group=(23.5,41,11,4,7734,236)
print(group[4])


groupA=(23.5,41,11,4,7734,236)
groupB=(663,32,457,2345)
groupC=groupA + groupB
print(groupC)


groupA=set([23.5,41,11,4,7734,236,7734])
groupA.add(1400)
groupA.remove(7734)
print(groupA)

groupA={23.5,41,11,4,7734,236}
groupB={663,32,457,2345}
print(groupA | groupB)
print(groupA.union(groupB))

groupA={23.5,41,11,4,7734,236}
groupB={663,32,457,2345,7734,236}
print(groupA&groupB)
print(groupA.intersection(groupB))

x=10
while x>2:
    print(x)
    x=x-1
print("go!")

x=0
n=10
while x<=n:
    print(x)
    if x==4:
        break
    x=x+1

n=5
while n>0:
    n-=1
    if n==2:
        continue
    print(n)
print("loop ended.")

Hello World!
i love coding
Charles Owuala
my name is charles
Hello charles, you are 27 today
hello Charles
e
challenge
Constance
CONSTANCE
constance
Wecome to Ghana, Clarke.
33
True
False
equal
daniel
['goat', 'pig', 'fowl']
goat
30
['geoffery', 34, 'Maria', 'ope']
[4, 11, 23.5, 41, 236, 7734]
<class 'list'>
[23.5, 41, 11, 4, 7734, 236, 'one million']
[23.5, 41, 11, 4, 7734, 236, 'one million', 'gore-fest']
1
 7734 is the highest value in the group
 4 is the lowest value in the group
6
7734
(23.5, 41, 11, 4, 7734, 236, 663, 32, 457, 2345)
{4, 41, 11, 236, 23.5, 1400}
{32, 4, 663, 41, 457, 11, 236, 2345, 7734, 23.5}
{32, 4, 663, 41, 457, 11, 236, 2345, 7734, 23.5}
{236, 7734}
{236, 7734}
10
9
8
7
6
5
4
3
go!
0
1
2
3
4
4
3
1
0
loop ended.